find_library(GM2Calc_LIBRARY NAMES ${CONAN_LIBS_GM2CALC} PATHS ${CONAN_LIB_DIRS_GM2CALC})
find_path(GM2Calc_INCLUDE_DIRS NAMES gm2calc/gm2_version.h PATHS ${CONAN_INCLUDE_DIRS_GM2CALC})

set(GM2Calc_FOUND TRUE)
set(GM2Calc_INCLUDE_DIRS ${GM2CALC_INCLUDE_DIR})
set(GM2Calc_LIBRARIES ${GM2Calc_LIBRARY})
mark_as_advanced(GM2Calc_LIBRARY GM2CALC_INCLUDE_DIR)

if(GM2Calc_FOUND AND NOT TARGET GM2Calc::GM2Calc)
  add_library(GM2Calc::GM2Calc UNKNOWN IMPORTED)
  set_target_properties(GM2Calc::GM2Calc PROPERTIES
    IMPORTED_LOCATION "${GM2Calc_LIBRARIES}"
    INTERFACE_INCLUDE_DIRECTORIES "${GM2Calc_INCLUDE_DIRS}"
  )
endif()
